name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: sudo gem install bundler -v 2.3.7
      - run: brew install shared-mime-info
        if: matrix.os == 'macos-latest'
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec rspec
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage.xml
